version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: mkdir ~/junit
            - run:
                command: mocha test --reporter mocha-junit-reporter
                environment:
                  MOCHA_FILE: ~/junit/test-results.xml
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit

workflows:
  build-and-test:
    jobs:
      - build-and-test
