version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/postgres:12.2
        environment:
          - POSTGRES_DB=sales_cashback
          - POSTGRES_USER=sales_cashback
          - POSTGRES_PASSWORD=sales_cashback
      - image: circleci/node:13.13.0
  build-and-test:
    executor:
      name: node/13.13.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build-database
            - run: npm test
            - run: npm run coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
