  /v1/products:
    get:
      tags:
      - "Products"
      security:
      - auth: []
      summary: "Products elements"
      description: "This for authenticate users to get a list of all products."
      operationId: "getListOfProducts"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductList"
        400:
          description: "Bad Request"
